In [1]:
import numpy as np

random_matrix = np.random.randint(1, 51, (3, 3))

In [2]:
print(random_matrix )

[[33 12  2]
 [33 39 11]
 [40 47 19]]


In [3]:
np.random.seed(10)
random = np.random.randint(1, 51, (3, 3))
print(random)

[[33 12  2]
 [33 39 11]
 [40 47 19]]


In [4]:
print(random)

[[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [5]:
random_matrix = np.random.randint(1, 51, (3, 3))
print(random_matrix)

[[30 50  9]
 [10  1 43]
 [41 37 17]]


**Observe and explain the differences in outputs.**

-  a fixed seed NumPy ensures that the same random numbers are generated every time the code runs. This makes results reproducible.Without setting a seed, NumPy generates truly random numbers each time the script is run. As a result, the matrix values will change with every execution.